trigger:
  branches:
    include:
     - main
     - master
  paths:
    include:
     - /Root/Dev

pool: Default


stages:
- stage: InfraCreateForAKS
  displayName: "Aks Infra Create"
  jobs:
  - job: InfraJobForAks
    displayName: "Aks Infra Job"
    steps:
     - task: TerraformInstaller@1
       inputs:
         terraformVersion: 'latest'
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'init'
         backendServiceArm: 'humAzure'
         backendAzureRmResourceGroupName: 'myman-rg'
         backendAzureRmStorageAccountName: 'mycvffdgfd434gffbvvbc444'
         backendAzureRmContainerName: 'mycontainer'
         backendAzureRmKey: 'ram.terraform.tfstate'
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'validate'
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'custom'
         outputTo: 'console'
         customCommand: 'fmt'
         environmentServiceNameAzureRM: 'humAzure'
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'plan'
         environmentServiceNameAzureRM: 'humAzure'
     - task: TerraformTaskV4@4
       inputs:
         provider: 'azurerm'
         command: 'apply'
         commandOptions: '--auto-approve'
         environmentServiceNameAzureRM: 'humAzure'