apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-html-calculator
        image: myacr0216.azurecr.io/my-html-calculator:v1
        ports:
        - containerPort: 80
      imagePullSecrets:
      - name: acr-secret



